[package]
name = "horsenuggets/commandline-luau"
description = "A CLI builder for Luau."
version = "0.0.1"
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/horsenuggets/commandline-luau"

[dependencies]
Chalk = "horsenuggets/chalk-luau@0.0.0"
t = "horsenuggets/t@3.1.1-horse.0.3"

[dev-dependencies]
Testable = "horsenuggets/testable@0.0.5"
